apiVersion: operator.kube-spin.mrezhi.net/v1alpha1
kind: WasmApp
metadata:
  name: float-operation-app
  namespace: webassembly
spec:
  replicas: 1
  ociImage: artifacts.apps.mrezhi.net/wasm/spin/go/float-operation
  ociImageTag: v1
  outboundHttp: false
  runtimeClass: spin
  imagePullSecret: artifacts-wasm-registry
  ingressEnabled: true
  ingressClass: nginx
  ingressHost: float-operation.l26.mrezhi.net
  ingressTlsEnabled: true