apiVersion: operator.kube-spin.mrezhi.net/v1alpha1
kind: WasmApp
metadata:
  name: whatlang-app
  namespace: webassembly
spec:
  replicas: 1
  ociImage: artifacts.apps.mrezhi.net/wasm/spin/rust/whatlang
  ociImageTag: v1
  outboundHttp: true
  runtimeClass: spin
  imagePullSecret: artifacts-wasm-registry
  ingressEnabled: true
  ingressClass: nginx
  ingressHost: whatlang.l26.mrezhi.net
  ingressTlsEnabled: true