spin_version = "1"
authors = ["vojdan"]
description = ""
name = "prime-numbers"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "prime-numbers"
source = "target/wasm32-wasi/release/prime_numbers.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
