spin_version = "1"
authors = ["vojdan"]
description = ""
name = "matmul"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "matmul"
source = "main.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "tinygo build -wasm-abi=generic -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
