"""Add base table

Revision ID: c0aee863e363
Revises: 
Create Date: 2023-01-29 13:16:36.105271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0aee863e363'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('k8s_pods_schedule_info',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('namespace', sa.String(), nullable=True),
    sa.Column('pod_name', sa.String(), nullable=False),
    sa.Column('time_scheduled', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_ready', sa.DateTime(timezone=True), nullable=True),
    sa.Column('test_batch', sa.String(), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace', 'pod_name')
    )
    op.create_index(op.f('ix_k8s_pods_schedule_info_namespace'), 'k8s_pods_schedule_info', ['namespace'], unique=False)
    op.create_index(op.f('ix_k8s_pods_schedule_info_pod_name'), 'k8s_pods_schedule_info', ['pod_name'], unique=False)
    op.create_index(op.f('ix_k8s_pods_schedule_info_test_batch'), 'k8s_pods_schedule_info', ['test_batch'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_k8s_pods_schedule_info_test_batch'), table_name='k8s_pods_schedule_info')
    op.drop_index(op.f('ix_k8s_pods_schedule_info_pod_name'), table_name='k8s_pods_schedule_info')
    op.drop_index(op.f('ix_k8s_pods_schedule_info_namespace'), table_name='k8s_pods_schedule_info')
    op.drop_table('k8s_pods_schedule_info')
    # ### end Alembic commands ###
